# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.api.payment_api import PaymentApi


class TestPaymentApi(unittest.TestCase):
    """PaymentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentApi()

    def tearDown(self) -> None:
        pass

    def test_get_payment_by_id(self) -> None:
        """Test case for get_payment_by_id

        Get payment details
        """
        pass

    def test_post_payment(self) -> None:
        """Test case for post_payment

        Create a new payment
        """
        pass


if __name__ == '__main__':
    unittest.main()
