# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.models.get_organization_by_id200_response_data import GetOrganizationById200ResponseData

class TestGetOrganizationById200ResponseData(unittest.TestCase):
    """GetOrganizationById200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOrganizationById200ResponseData:
        """Test GetOrganizationById200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOrganizationById200ResponseData`
        """
        model = GetOrganizationById200ResponseData()
        if include_optional:
            return GetOrganizationById200ResponseData(
                id = '',
                name = '',
                phone_number = '',
                website = ''
            )
        else:
            return GetOrganizationById200ResponseData(
                id = '',
                name = '',
                phone_number = '',
                website = '',
        )
        """

    def testGetOrganizationById200ResponseData(self):
        """Test GetOrganizationById200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
