# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.models.payment_get_data import PaymentGetData

class TestPaymentGetData(unittest.TestCase):
    """PaymentGetData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentGetData:
        """Test PaymentGetData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentGetData`
        """
        model = PaymentGetData()
        if include_optional:
            return PaymentGetData(
                id = '',
                amount = -2147483648,
                phone_number = '',
                pass_code = '',
                status = 'pending',
                environment_id = '',
                payment_request_id = '',
                configuration_id = '',
                reference_id = '',
                metadata = None,
                payout_id = '',
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PaymentGetData(
                id = '',
                amount = -2147483648,
                phone_number = '',
                pass_code = '',
                status = 'pending',
                environment_id = '',
                payment_request_id = '',
                configuration_id = '',
                reference_id = '',
                metadata = None,
                payout_id = '',
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPaymentGetData(self):
        """Test PaymentGetData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
