# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.models.get_organization_by_id200_response import GetOrganizationById200Response

class TestGetOrganizationById200Response(unittest.TestCase):
    """GetOrganizationById200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOrganizationById200Response:
        """Test GetOrganizationById200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOrganizationById200Response`
        """
        model = GetOrganizationById200Response()
        if include_optional:
            return GetOrganizationById200Response(
                data = moosyl.models.get_organization_by_id_200_response_data.getOrganizationById_200_response_data(
                    id = '', 
                    name = '', 
                    phone_number = '', 
                    website = '', )
            )
        else:
            return GetOrganizationById200Response(
                data = moosyl.models.get_organization_by_id_200_response_data.getOrganizationById_200_response_data(
                    id = '', 
                    name = '', 
                    phone_number = '', 
                    website = '', ),
        )
        """

    def testGetOrganizationById200Response(self):
        """Test GetOrganizationById200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
