# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.models.checkout_session_create import CheckoutSessionCreate

class TestCheckoutSessionCreate(unittest.TestCase):
    """CheckoutSessionCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckoutSessionCreate:
        """Test CheckoutSessionCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckoutSessionCreate`
        """
        model = CheckoutSessionCreate()
        if include_optional:
            return CheckoutSessionCreate(
                data = moosyl.models.checkout_session_create_data.checkoutSession_create_data(
                    id = '', 
                    payment_request_id = '', 
                    environment_id = '', 
                    selected_configuration_id = '', 
                    status = 'open', 
                    success_url = '', 
                    cancel_url = '', 
                    expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                checkout_url = ''
            )
        else:
            return CheckoutSessionCreate(
                data = moosyl.models.checkout_session_create_data.checkoutSession_create_data(
                    id = '', 
                    payment_request_id = '', 
                    environment_id = '', 
                    selected_configuration_id = '', 
                    status = 'open', 
                    success_url = '', 
                    cancel_url = '', 
                    expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                checkout_url = '',
        )
        """

    def testCheckoutSessionCreate(self):
        """Test CheckoutSessionCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
