# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.api.checkout_session_api import CheckoutSessionApi


class TestCheckoutSessionApi(unittest.TestCase):
    """CheckoutSessionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CheckoutSessionApi()

    def tearDown(self) -> None:
        pass

    def test_get_checkout_session_public_by_id(self) -> None:
        """Test case for get_checkout_session_public_by_id

        Get public checkout session
        """
        pass

    def test_post_checkout_session(self) -> None:
        """Test case for post_checkout_session

        Create checkout session
        """
        pass

    def test_post_checkout_session_public_by_id_pay(self) -> None:
        """Test case for post_checkout_session_public_by_id_pay

        Pay public checkout session
        """
        pass

    def test_post_checkout_session_public_by_id_switch_method(self) -> None:
        """Test case for post_checkout_session_public_by_id_switch_method

        Switch public checkout method
        """
        pass


if __name__ == '__main__':
    unittest.main()
