# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.api.payment_request_api import PaymentRequestApi


class TestPaymentRequestApi(unittest.TestCase):
    """PaymentRequestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentRequestApi()

    def tearDown(self) -> None:
        pass

    def test_get_payment_request_by_id(self) -> None:
        """Test case for get_payment_request_by_id

        Get payment request
        """
        pass

    def test_get_payment_request_by_transaction_by_transaction_id(self) -> None:
        """Test case for get_payment_request_by_transaction_by_transaction_id

        Get payment request by transaction ID
        """
        pass

    def test_patch_payment_request_by_transaction_id_refresh_status(self) -> None:
        """Test case for patch_payment_request_by_transaction_id_refresh_status

        Refresh payment request status
        """
        pass

    def test_post_payment_request(self) -> None:
        """Test case for post_payment_request

        Create payment request
        """
        pass


if __name__ == '__main__':
    unittest.main()
