# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.api.subscriptions_api import SubscriptionsApi


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionsApi()

    def tearDown(self) -> None:
        pass

    def test_get_subscriptions(self) -> None:
        """Test case for get_subscriptions

        List subscriptions
        """
        pass

    def test_get_subscriptions_by_external_user_by_external_user_id(self) -> None:
        """Test case for get_subscriptions_by_external_user_by_external_user_id

        Get subscription by external user
        """
        pass

    def test_get_subscriptions_by_id(self) -> None:
        """Test case for get_subscriptions_by_id

        Get subscription
        """
        pass

    def test_post_subscriptions(self) -> None:
        """Test case for post_subscriptions

        Create subscription
        """
        pass

    def test_post_subscriptions_by_external_user(self) -> None:
        """Test case for post_subscriptions_by_external_user

        Create subscription by external user
        """
        pass

    def test_post_subscriptions_by_id_cancel(self) -> None:
        """Test case for post_subscriptions_by_id_cancel

        Cancel subscription
        """
        pass


if __name__ == '__main__':
    unittest.main()
