# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.api.products_api import ProductsApi


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductsApi()

    def tearDown(self) -> None:
        pass

    def test_get_products(self) -> None:
        """Test case for get_products

        List products or filter by id
        """
        pass

    def test_get_products_by_id(self) -> None:
        """Test case for get_products_by_id

        Get product with prices
        """
        pass

    def test_patch_products_by_id(self) -> None:
        """Test case for patch_products_by_id

        Update product
        """
        pass

    def test_patch_products_by_id_archive(self) -> None:
        """Test case for patch_products_by_id_archive

        Archive product
        """
        pass

    def test_post_products(self) -> None:
        """Test case for post_products

        Create product
        """
        pass


if __name__ == '__main__':
    unittest.main()
