# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.models.payment_request_create import PaymentRequestCreate

class TestPaymentRequestCreate(unittest.TestCase):
    """PaymentRequestCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentRequestCreate:
        """Test PaymentRequestCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentRequestCreate`
        """
        model = PaymentRequestCreate()
        if include_optional:
            return PaymentRequestCreate(
                phone_number = '',
                transaction_id = '',
                amount = None
            )
        else:
            return PaymentRequestCreate(
                transaction_id = '',
                amount = None,
        )
        """

    def testPaymentRequestCreate(self):
        """Test PaymentRequestCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
