# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.models.post_connect_exchange200_response_data import PostConnectExchange200ResponseData

class TestPostConnectExchange200ResponseData(unittest.TestCase):
    """PostConnectExchange200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostConnectExchange200ResponseData:
        """Test PostConnectExchange200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostConnectExchange200ResponseData`
        """
        model = PostConnectExchange200ResponseData()
        if include_optional:
            return PostConnectExchange200ResponseData(
                publishable_key = '',
                secret_key = '',
                webhook_secret = ''
            )
        else:
            return PostConnectExchange200ResponseData(
                publishable_key = '',
                secret_key = '',
                webhook_secret = '',
        )
        """

    def testPostConnectExchange200ResponseData(self):
        """Test PostConnectExchange200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
