# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.models.configuration_get import ConfigurationGet

class TestConfigurationGet(unittest.TestCase):
    """ConfigurationGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigurationGet:
        """Test ConfigurationGet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigurationGet`
        """
        model = ConfigurationGet()
        if include_optional:
            return ConfigurationGet(
                data = moosyl.models.configuration_get_data.configuration_get_data(
                    id = '', 
                    type = '', 
                    organization_id = '', 
                    config = null, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    is_testing_mode = True, )
            )
        else:
            return ConfigurationGet(
                data = moosyl.models.configuration_get_data.configuration_get_data(
                    id = '', 
                    type = '', 
                    organization_id = '', 
                    config = null, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    is_testing_mode = True, ),
        )
        """

    def testConfigurationGet(self):
        """Test ConfigurationGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
