# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.api.prices_api import PricesApi


class TestPricesApi(unittest.TestCase):
    """PricesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PricesApi()

    def tearDown(self) -> None:
        pass

    def test_get_prices_by_id(self) -> None:
        """Test case for get_prices_by_id

        Get price
        """
        pass

    def test_patch_prices_by_id(self) -> None:
        """Test case for patch_prices_by_id

        Update price
        """
        pass

    def test_patch_prices_by_id_archive(self) -> None:
        """Test case for patch_prices_by_id_archive

        Archive price
        """
        pass

    def test_post_prices(self) -> None:
        """Test case for post_prices

        Create price
        """
        pass


if __name__ == '__main__':
    unittest.main()
