# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.models.checkout_session_get import CheckoutSessionGet

class TestCheckoutSessionGet(unittest.TestCase):
    """CheckoutSessionGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckoutSessionGet:
        """Test CheckoutSessionGet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckoutSessionGet`
        """
        model = CheckoutSessionGet()
        if include_optional:
            return CheckoutSessionGet(
                data = moosyl.models.checkout_session_create_data.checkoutSession_create_data(
                    id = '', 
                    payment_request_id = '', 
                    environment_id = '', 
                    selected_configuration_id = '', 
                    status = 'open', 
                    success_url = '', 
                    cancel_url = '', 
                    expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                organization = moosyl.models.get_organization_by_id_200_response_data.getOrganizationById_200_response_data(
                    id = '', 
                    name = '', 
                    phone_number = '', 
                    website = '', ),
                payment_request = moosyl.models.payment_request_get_data.paymentRequest_get_data(
                    id = '', 
                    amount = -2147483648, 
                    total_amount = -2147483648, 
                    phone_number = '', 
                    transaction_id = '', 
                    environment_id = '', 
                    retry_count = -2147483648, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                configurations = [
                    moosyl.models.configuration_list_data_inner.configuration_list_data_inner(
                        id = '', 
                        type = '', 
                        organization_id = '', 
                        config = null, 
                        is_testing_mode = True, )
                    ],
                latest_payment = moosyl.models.checkout_session_get_latest_payment.checkoutSession_get_latestPayment(
                    id = '', 
                    amount = 1.337, 
                    status = '', 
                    reference_id = '', 
                    payment_code = '', )
            )
        else:
            return CheckoutSessionGet(
                data = moosyl.models.checkout_session_create_data.checkoutSession_create_data(
                    id = '', 
                    payment_request_id = '', 
                    environment_id = '', 
                    selected_configuration_id = '', 
                    status = 'open', 
                    success_url = '', 
                    cancel_url = '', 
                    expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                organization = moosyl.models.get_organization_by_id_200_response_data.getOrganizationById_200_response_data(
                    id = '', 
                    name = '', 
                    phone_number = '', 
                    website = '', ),
                payment_request = moosyl.models.payment_request_get_data.paymentRequest_get_data(
                    id = '', 
                    amount = -2147483648, 
                    total_amount = -2147483648, 
                    phone_number = '', 
                    transaction_id = '', 
                    environment_id = '', 
                    retry_count = -2147483648, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                configurations = [
                    moosyl.models.configuration_list_data_inner.configuration_list_data_inner(
                        id = '', 
                        type = '', 
                        organization_id = '', 
                        config = null, 
                        is_testing_mode = True, )
                    ],
        )
        """

    def testCheckoutSessionGet(self):
        """Test CheckoutSessionGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
