# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.models.subscription_list import SubscriptionList

class TestSubscriptionList(unittest.TestCase):
    """SubscriptionList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionList:
        """Test SubscriptionList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionList`
        """
        model = SubscriptionList()
        if include_optional:
            return SubscriptionList(
                data = [
                    moosyl.models.subscription_get_data.subscription_get_data(
                        id = '', 
                        organization_id = '', 
                        customer_id = '', 
                        price_id = '', 
                        status = 'trialing', 
                        next_billing_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        cancelled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pagination = moosyl.models.product_list_pagination.product_list_pagination(
                    page = 1.337, 
                    limit = 1.337, 
                    total = 1.337, 
                    total_pages = 1.337, )
            )
        else:
            return SubscriptionList(
                data = [
                    moosyl.models.subscription_get_data.subscription_get_data(
                        id = '', 
                        organization_id = '', 
                        customer_id = '', 
                        price_id = '', 
                        status = 'trialing', 
                        next_billing_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        cancelled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pagination = moosyl.models.product_list_pagination.product_list_pagination(
                    page = 1.337, 
                    limit = 1.337, 
                    total = 1.337, 
                    total_pages = 1.337, ),
        )
        """

    def testSubscriptionList(self):
        """Test SubscriptionList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
