# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.models.delete_connect_revoke_request import DeleteConnectRevokeRequest

class TestDeleteConnectRevokeRequest(unittest.TestCase):
    """DeleteConnectRevokeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteConnectRevokeRequest:
        """Test DeleteConnectRevokeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteConnectRevokeRequest`
        """
        model = DeleteConnectRevokeRequest()
        if include_optional:
            return DeleteConnectRevokeRequest(
                platform_id = '',
                platform_secret = '',
                connection_id = ''
            )
        else:
            return DeleteConnectRevokeRequest(
                platform_id = '',
                platform_secret = '',
                connection_id = '',
        )
        """

    def testDeleteConnectRevokeRequest(self):
        """Test DeleteConnectRevokeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
