# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.models.subscription_create_by_external_user import SubscriptionCreateByExternalUser

class TestSubscriptionCreateByExternalUser(unittest.TestCase):
    """SubscriptionCreateByExternalUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionCreateByExternalUser:
        """Test SubscriptionCreateByExternalUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionCreateByExternalUser`
        """
        model = SubscriptionCreateByExternalUser()
        if include_optional:
            return SubscriptionCreateByExternalUser(
                external_user_id = '',
                phone = '',
                price_id = '',
                trial = None,
                trial_period = '1_week',
                trial_end = None,
                started_at = None,
                expires_at = None
            )
        else:
            return SubscriptionCreateByExternalUser(
                external_user_id = '',
                price_id = '',
        )
        """

    def testSubscriptionCreateByExternalUser(self):
        """Test SubscriptionCreateByExternalUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
