# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.api.connect_api import ConnectApi


class TestConnectApi(unittest.TestCase):
    """ConnectApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectApi()

    def tearDown(self) -> None:
        pass

    def test_delete_connect_revoke(self) -> None:
        """Test case for delete_connect_revoke

        Revoke a platform connection
        """
        pass

    def test_post_connect_exchange(self) -> None:
        """Test case for post_connect_exchange

        Exchange authorization code for API credentials
        """
        pass


if __name__ == '__main__':
    unittest.main()
