# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moosyl.api.customers_api import CustomersApi


class TestCustomersApi(unittest.TestCase):
    """CustomersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomersApi()

    def tearDown(self) -> None:
        pass

    def test_get_customers(self) -> None:
        """Test case for get_customers

        List customers or filter by id/external user
        """
        pass

    def test_patch_customers_by_id(self) -> None:
        """Test case for patch_customers_by_id

        Update customer
        """
        pass

    def test_post_customers(self) -> None:
        """Test case for post_customers

        Create customer
        """
        pass


if __name__ == '__main__':
    unittest.main()
