# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CheckoutSessionCreateData(BaseModel):
    """
    CheckoutSessionCreateData
    """ # noqa: E501
    id: UUID
    payment_request_id: UUID = Field(alias="paymentRequestId")
    environment_id: UUID = Field(alias="environmentId")
    selected_configuration_id: Optional[UUID] = Field(alias="selectedConfigurationId")
    status: StrictStr
    success_url: Optional[StrictStr] = Field(alias="successUrl")
    cancel_url: Optional[StrictStr] = Field(alias="cancelUrl")
    expires_at: datetime = Field(alias="expiresAt")
    completed_at: Optional[datetime] = Field(alias="completedAt")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "paymentRequestId", "environmentId", "selectedConfigurationId", "status", "successUrl", "cancelUrl", "expiresAt", "completedAt", "createdAt", "updatedAt"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['open', 'completed', 'expired', 'cancelled']):
            raise ValueError("must be one of enum values ('open', 'completed', 'expired', 'cancelled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CheckoutSessionCreateData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if selected_configuration_id (nullable) is None
        # and model_fields_set contains the field
        if self.selected_configuration_id is None and "selected_configuration_id" in self.model_fields_set:
            _dict['selectedConfigurationId'] = None

        # set to None if success_url (nullable) is None
        # and model_fields_set contains the field
        if self.success_url is None and "success_url" in self.model_fields_set:
            _dict['successUrl'] = None

        # set to None if cancel_url (nullable) is None
        # and model_fields_set contains the field
        if self.cancel_url is None and "cancel_url" in self.model_fields_set:
            _dict['cancelUrl'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CheckoutSessionCreateData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "paymentRequestId": obj.get("paymentRequestId"),
            "environmentId": obj.get("environmentId"),
            "selectedConfigurationId": obj.get("selectedConfigurationId"),
            "status": obj.get("status"),
            "successUrl": obj.get("successUrl"),
            "cancelUrl": obj.get("cancelUrl"),
            "expiresAt": obj.get("expiresAt"),
            "completedAt": obj.get("completedAt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


