# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from moosyl.models.checkout_session_create_data import CheckoutSessionCreateData
from moosyl.models.checkout_session_get_latest_payment import CheckoutSessionGetLatestPayment
from moosyl.models.configuration_list_data_inner import ConfigurationListDataInner
from moosyl.models.get_organization_by_id200_response_data import GetOrganizationById200ResponseData
from moosyl.models.payment_request_get_data import PaymentRequestGetData
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CheckoutSessionGet(BaseModel):
    """
    CheckoutSessionGet
    """ # noqa: E501
    data: CheckoutSessionCreateData
    organization: GetOrganizationById200ResponseData
    payment_request: PaymentRequestGetData = Field(alias="paymentRequest")
    configurations: List[ConfigurationListDataInner]
    latest_payment: Optional[CheckoutSessionGetLatestPayment] = Field(default=None, alias="latestPayment")
    __properties: ClassVar[List[str]] = ["data", "organization", "paymentRequest", "configurations", "latestPayment"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CheckoutSessionGet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of organization
        if self.organization:
            _dict['organization'] = self.organization.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment_request
        if self.payment_request:
            _dict['paymentRequest'] = self.payment_request.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in configurations (list)
        _items = []
        if self.configurations:
            for _item_configurations in self.configurations:
                if _item_configurations:
                    _items.append(_item_configurations.to_dict())
            _dict['configurations'] = _items
        # override the default output from pydantic by calling `to_dict()` of latest_payment
        if self.latest_payment:
            _dict['latestPayment'] = self.latest_payment.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CheckoutSessionGet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "data": CheckoutSessionCreateData.from_dict(obj["data"]) if obj.get("data") is not None else None,
            "organization": GetOrganizationById200ResponseData.from_dict(obj["organization"]) if obj.get("organization") is not None else None,
            "paymentRequest": PaymentRequestGetData.from_dict(obj["paymentRequest"]) if obj.get("paymentRequest") is not None else None,
            "configurations": [ConfigurationListDataInner.from_dict(_item) for _item in obj["configurations"]] if obj.get("configurations") is not None else None,
            "latestPayment": CheckoutSessionGetLatestPayment.from_dict(obj["latestPayment"]) if obj.get("latestPayment") is not None else None
        })
        return _obj


