# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from moosyl.models.get_products_page_parameter import GetProductsPageParameter
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CheckoutSessionCreateBody(BaseModel):
    """
    CheckoutSessionCreateBody
    """ # noqa: E501
    payment_request_id: Optional[StrictStr] = Field(default=None, alias="paymentRequestId")
    transaction_id: Optional[StrictStr] = Field(default=None, alias="transactionId")
    amount: Optional[GetProductsPageParameter] = None
    phone_number: Optional[StrictStr] = Field(default=None, alias="phoneNumber")
    success_url: Optional[StrictStr] = Field(default=None, alias="successUrl")
    cancel_url: Optional[StrictStr] = Field(default=None, alias="cancelUrl")
    expires_in_minutes: Optional[Union[Annotated[float, Field(le=1440, strict=True, ge=5)], Annotated[int, Field(le=1440, strict=True, ge=5)]]] = Field(default=None, alias="expiresInMinutes")
    __properties: ClassVar[List[str]] = ["paymentRequestId", "transactionId", "amount", "phoneNumber", "successUrl", "cancelUrl", "expiresInMinutes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CheckoutSessionCreateBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CheckoutSessionCreateBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "paymentRequestId": obj.get("paymentRequestId"),
            "transactionId": obj.get("transactionId"),
            "amount": GetProductsPageParameter.from_dict(obj["amount"]) if obj.get("amount") is not None else None,
            "phoneNumber": obj.get("phoneNumber"),
            "successUrl": obj.get("successUrl"),
            "cancelUrl": obj.get("cancelUrl"),
            "expiresInMinutes": obj.get("expiresInMinutes")
        })
        return _obj


