# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PaymentGetData(BaseModel):
    """
    PaymentGetData
    """ # noqa: E501
    id: UUID
    amount: Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]
    phone_number: Optional[StrictStr] = Field(alias="phoneNumber")
    pass_code: Optional[StrictStr] = Field(alias="passCode")
    status: StrictStr
    environment_id: UUID = Field(alias="environmentId")
    payment_request_id: UUID = Field(alias="paymentRequestId")
    configuration_id: UUID = Field(alias="configurationId")
    reference_id: Optional[StrictStr] = Field(alias="referenceId")
    metadata: Optional[Any]
    payout_id: Optional[UUID] = Field(alias="payoutId")
    completed_at: Optional[datetime] = Field(alias="completedAt")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "amount", "phoneNumber", "passCode", "status", "environmentId", "paymentRequestId", "configurationId", "referenceId", "metadata", "payoutId", "completedAt", "createdAt", "updatedAt"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'completed', 'failed', 'cancelled']):
            raise ValueError("must be one of enum values ('pending', 'completed', 'failed', 'cancelled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentGetData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if phone_number (nullable) is None
        # and model_fields_set contains the field
        if self.phone_number is None and "phone_number" in self.model_fields_set:
            _dict['phoneNumber'] = None

        # set to None if pass_code (nullable) is None
        # and model_fields_set contains the field
        if self.pass_code is None and "pass_code" in self.model_fields_set:
            _dict['passCode'] = None

        # set to None if reference_id (nullable) is None
        # and model_fields_set contains the field
        if self.reference_id is None and "reference_id" in self.model_fields_set:
            _dict['referenceId'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if payout_id (nullable) is None
        # and model_fields_set contains the field
        if self.payout_id is None and "payout_id" in self.model_fields_set:
            _dict['payoutId'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentGetData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "amount": obj.get("amount"),
            "phoneNumber": obj.get("phoneNumber"),
            "passCode": obj.get("passCode"),
            "status": obj.get("status"),
            "environmentId": obj.get("environmentId"),
            "paymentRequestId": obj.get("paymentRequestId"),
            "configurationId": obj.get("configurationId"),
            "referenceId": obj.get("referenceId"),
            "metadata": obj.get("metadata"),
            "payoutId": obj.get("payoutId"),
            "completedAt": obj.get("completedAt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


