# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PostCheckoutSessionPublicByIdPay200Response(BaseModel):
    """
    PostCheckoutSessionPublicByIdPay200Response
    """ # noqa: E501
    status: StrictStr
    reference_id: Optional[StrictStr] = Field(default=None, alias="referenceId")
    payment_code: Optional[StrictStr] = Field(default=None, alias="paymentCode")
    success_url: Optional[StrictStr] = Field(default=None, alias="successUrl")
    provider: Optional[StrictStr] = None
    form_data: Optional[Any] = Field(default=None, alias="formData")
    __properties: ClassVar[List[str]] = ["status", "referenceId", "paymentCode", "successUrl", "provider", "formData"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostCheckoutSessionPublicByIdPay200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if reference_id (nullable) is None
        # and model_fields_set contains the field
        if self.reference_id is None and "reference_id" in self.model_fields_set:
            _dict['referenceId'] = None

        # set to None if success_url (nullable) is None
        # and model_fields_set contains the field
        if self.success_url is None and "success_url" in self.model_fields_set:
            _dict['successUrl'] = None

        # set to None if form_data (nullable) is None
        # and model_fields_set contains the field
        if self.form_data is None and "form_data" in self.model_fields_set:
            _dict['formData'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostCheckoutSessionPublicByIdPay200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "referenceId": obj.get("referenceId"),
            "paymentCode": obj.get("paymentCode"),
            "successUrl": obj.get("successUrl"),
            "provider": obj.get("provider"),
            "formData": obj.get("formData")
        })
        return _obj


