# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from moosyl.models.subscription_create_trial import SubscriptionCreateTrial
from moosyl.models.subscription_create_trial_end import SubscriptionCreateTrialEnd
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SubscriptionCreate(BaseModel):
    """
    SubscriptionCreate
    """ # noqa: E501
    id: Optional[UUID] = None
    customer_id: UUID = Field(alias="customerId")
    price_id: UUID = Field(alias="priceId")
    cancelled_at: Optional[datetime] = Field(default=None, alias="cancelledAt")
    expires_at: Optional[datetime] = Field(default=None, alias="expiresAt")
    trial: Optional[SubscriptionCreateTrial] = None
    trial_period: Optional[StrictStr] = Field(default=None, alias="trialPeriod")
    trial_end: Optional[SubscriptionCreateTrialEnd] = Field(default=None, alias="trialEnd")
    started_at: Optional[SubscriptionCreateTrialEnd] = Field(default=None, alias="startedAt")
    __properties: ClassVar[List[str]] = ["id", "customerId", "priceId", "cancelledAt", "expiresAt", "trial", "trialPeriod", "trialEnd", "startedAt"]

    @field_validator('trial_period')
    def trial_period_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['1_week', '1_month', '1_year']):
            raise ValueError("must be one of enum values ('1_week', '1_month', '1_year')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of trial
        if self.trial:
            _dict['trial'] = self.trial.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trial_end
        if self.trial_end:
            _dict['trialEnd'] = self.trial_end.to_dict()
        # override the default output from pydantic by calling `to_dict()` of started_at
        if self.started_at:
            _dict['startedAt'] = self.started_at.to_dict()
        # set to None if cancelled_at (nullable) is None
        # and model_fields_set contains the field
        if self.cancelled_at is None and "cancelled_at" in self.model_fields_set:
            _dict['cancelledAt'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expiresAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "customerId": obj.get("customerId"),
            "priceId": obj.get("priceId"),
            "cancelledAt": obj.get("cancelledAt"),
            "expiresAt": obj.get("expiresAt"),
            "trial": SubscriptionCreateTrial.from_dict(obj["trial"]) if obj.get("trial") is not None else None,
            "trialPeriod": obj.get("trialPeriod"),
            "trialEnd": SubscriptionCreateTrialEnd.from_dict(obj["trialEnd"]) if obj.get("trialEnd") is not None else None,
            "startedAt": SubscriptionCreateTrialEnd.from_dict(obj["startedAt"]) if obj.get("startedAt") is not None else None
        })
        return _obj


