# coding: utf-8

"""
    Moosyl API

    The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SubscriptionGetData(BaseModel):
    """
    SubscriptionGetData
    """ # noqa: E501
    id: UUID
    organization_id: UUID = Field(alias="organizationId")
    customer_id: UUID = Field(alias="customerId")
    price_id: UUID = Field(alias="priceId")
    status: StrictStr
    next_billing_date: Optional[datetime] = Field(alias="nextBillingDate")
    started_at: Optional[datetime] = Field(alias="startedAt")
    cancelled_at: Optional[datetime] = Field(alias="cancelledAt")
    expires_at: Optional[datetime] = Field(alias="expiresAt")
    __properties: ClassVar[List[str]] = ["id", "organizationId", "customerId", "priceId", "status", "nextBillingDate", "startedAt", "cancelledAt", "expiresAt"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['trialing', 'active', 'past_due', 'paused', 'cancelled', 'expired', 'pending_cancellation']):
            raise ValueError("must be one of enum values ('trialing', 'active', 'past_due', 'paused', 'cancelled', 'expired', 'pending_cancellation')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionGetData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if next_billing_date (nullable) is None
        # and model_fields_set contains the field
        if self.next_billing_date is None and "next_billing_date" in self.model_fields_set:
            _dict['nextBillingDate'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['startedAt'] = None

        # set to None if cancelled_at (nullable) is None
        # and model_fields_set contains the field
        if self.cancelled_at is None and "cancelled_at" in self.model_fields_set:
            _dict['cancelledAt'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expiresAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionGetData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "organizationId": obj.get("organizationId"),
            "customerId": obj.get("customerId"),
            "priceId": obj.get("priceId"),
            "status": obj.get("status"),
            "nextBillingDate": obj.get("nextBillingDate"),
            "startedAt": obj.get("startedAt"),
            "cancelledAt": obj.get("cancelledAt"),
            "expiresAt": obj.get("expiresAt")
        })
        return _obj


